Let's give ourselves a matrix to start with

In [39]:
import numpy as np

A = np.array([
    [4, 1, 3],
    [2, 8, 2],
    [1, 2, 1],
])

U, S, Vt = np.linalg.svd(A)

print("Left singular")
print(U)
print("Sigma")
print(np.diag(S))
print("Right singular")
print(Vt)

Left singular
[[-0.36255872  0.92069219 -0.14448898]
 [-0.89441613 -0.38730766 -0.22363489]
 [-0.26186058  0.04815249  0.96390372]]
Sigma
[[9.31522027 0.         0.        ]
 [0.         4.14921209 0.        ]
 [0.         0.         0.10349068]]
Right singular
[[-0.37582876 -0.8632763  -0.33690765]
 [ 0.71249815 -0.50165286  0.49060248]
 [-0.59253618 -0.05566356  0.80361834]]


Let's do a quick check to make sure we get back where we wanted

In [40]:
print(U @ np.diag(S) @ Vt)

[[4. 1. 3.]
 [2. 8. 2.]
 [1. 2. 1.]]


And that's a little boring, so, let's do the steps ourselves, first let's grab the transpose

In [41]:
a_transpose_a = A.T @ A

We know that this produces a symmetric matrix, so, we can use the faster algorithm to get the eigenvalues

In [42]:
a_transpose_a_eigen_values, a_transpose_a_eigen_vectors = np.linalg.eigh(a_transpose_a)
print("(A^T)A eigen values")
print(a_transpose_a_eigen_values)
print("(A^T)A eigen vectors")
print(a_transpose_a_eigen_vectors)

(A^T)A eigen values
[1.07103202e-02 1.72159610e+01 8.67733287e+01]
(A^T)A eigen vectors
[[-0.59253618 -0.71249815 -0.37582876]
 [-0.05566356  0.50165286 -0.8632763 ]
 [ 0.80361834 -0.49060248 -0.33690765]]


In [43]:
# 1. Get the sort indices (High to Low)
sort_indices = np.argsort(a_transpose_a_eigen_values)[::-1]

# 2. Reorder Eigenvalues
sorted_eigenvalues = a_transpose_a_eigen_values[sort_indices]

# 3. Reorder Eigenvectors (Columns)
# We use [:, sort_indices] to shuffle columns, keeping rows intact
sorted_eigenvectors = a_transpose_a_eigen_vectors[:, sort_indices]

print("(A^T)A eigen values sorted")
print(sorted_eigenvalues)
# Expected: [8.  2.]

print("(A^T)A eigen vectors sorted")
print(sorted_eigenvectors)
# Expected: Columns matching the order of 8 and 2

(A^T)A eigen values sorted
[8.67733287e+01 1.72159610e+01 1.07103202e-02]
(A^T)A eigen vectors sorted
[[-0.37582876 -0.71249815 -0.59253618]
 [-0.8632763   0.50165286 -0.05566356]
 [-0.33690765 -0.49060248  0.80361834]]


We can then compose the singular values from the eigenvalues, and create a diagonal matrix with these entries

In [44]:
singular_values = np.sqrt(sorted_eigenvalues)
sigma = np.diag(singular_values)
print("sigma")
print(sigma)

sigma
[[9.31522027 0.         0.        ]
 [0.         4.14921209 0.        ]
 [0.         0.         0.10349068]]


Lastly we want our left singular vectors, which we can get by the formula U = A V Σ⁻¹

In [45]:
left_singular = (A @ sorted_eigenvectors) / singular_values
print("left singular")
print(left_singular)

print("result")
print(left_singular @ sigma @ (sorted_eigenvectors.T))

left singular
[[-0.36255872 -0.92069219 -0.14448898]
 [-0.89441613  0.38730766 -0.22363489]
 [-0.26186058 -0.04815249  0.96390372]]
result
[[4. 1. 3.]
 [2. 8. 2.]
 [1. 2. 1.]]


cool, checked that it works with higher dimensions