Alright, first, let's copy down what we're given and check

In [34]:
import numpy as np

A = np.array(
    [[677, -52, -66, -639, 386],
     [603, -15, -234, -799, 722],
     [0, 23, 551, -305, 240],
     [574, 72, -439, -842, 474],
     [299, 111, 414, -399, -12]
    ]
)

print(A)


[[ 677  -52  -66 -639  386]
 [ 603  -15 -234 -799  722]
 [   0   23  551 -305  240]
 [ 574   72 -439 -842  474]
 [ 299  111  414 -399  -12]]


We want to find the eigenvalues of $\mathbf{A}$
We can suppose that as $dim(col(\mathbf{A}))=rank(\mathbf{A})$.  
To be equal to $n$, then see where we get with that.  
Let's also give ourself a few things here to set the loop up for later

In [35]:
tolerance = 1e-4
eigenvalues_total = A.shape[0] # It's an nxn, so nbd to take n
eigenvalues_found = 0
eigenvalues_list = []
loop_counter = 0
A1 = A.copy()

That should conclude the setup. We're going to keep looping until we find them all

In [36]:
while eigenvalues_found < eigenvalues_total:
    print(f"for iteration {loop_counter}")
    loop_counter += 1
    Mu = A[-1,-1] # Grab the bottom right most
    Q, R = np.linalg.qr(A1-Mu*np.identity(A1.shape[0])) # So, the QR factorization of the matrix - Mu*I
    RQ = (R @ Q) # Multiply the two together
    A1 = RQ + Mu*np.identity(A1.shape[0]) # Then follow the process
    print(A1)

    # We want now to check our stopping conditions, if we find a lower diagonal < tolerance, we're close enough
    for j in range(A1.shape[0] - 1): # 0 through dim(col(A)) - 1
        if (abs(A1[j+1, j])) < tolerance:
            print(f"avast, me hearties, an eigenvalue on yond horizon, that be number {eigenvalues_found+1}")
            print(f"and it be values somewhat like {np.round(A1[-1,-1], 4)}") # Rounding to tolerance
            eigenvalues_list.append(float(np.round(A1[-1,-1], 4))) # As a float so python doesn't complain
            eigenvalues_found += 1
            
            # For a two by two we can take top-left and bottom-right
            if A1.shape[0] == 2:
                print(f"by Davey Jones, and another, that be number {eigenvalues_found+1}")
                print(f"and it look to be about {np.round(A1[0,0], 4)}") # Grab the top left too
                eigenvalues_list.append(float(np.round(A1[0,0], 4))) # As a float so python doesn't complain
                eigenvalues_found += 2
            
            A1 = A1[:-1,:-1] # Drop the right column and bottom row
            break

print(f"we found {eigenvalues_found-1} being {eigenvalues_list}")

for iteration 0
[[  233.21720051  -527.88641731  1231.65697137 -1361.11727681
    463.38262248]
 [  -58.63319577  -129.78239862   279.03035221   218.30836578
    125.83874352]
 [  -40.30042787    93.21747411   545.31810086   494.02250728
   -135.86278097]
 [  -51.08530815   179.67754661   323.54814301  -303.59029032
    225.02323125]
 [   35.86033983    98.03288334    49.11021166   -64.09487423
     13.83738756]]
for iteration 1
[[  514.46143294  -227.35507225  -131.84707834 -1673.15734406
    171.78962156]
 [   38.7367553   -320.31387392   147.32863464  -246.64108523
    150.31593055]
 [  -96.72148486  -122.22332239   632.1107599   -800.82483006
     90.64912426]
 [  162.52933848     8.00468357  -341.146379    -535.38821045
   -256.78922653]
 [  -13.78970039    55.7739963     -9.12931723    20.27779175
     68.12989154]]
for iteration 2
[[   89.51573652    26.7158614    519.84952811 -1655.99187821
   -109.00144305]
 [ -288.70906467     5.07786809   747.93428698  -322.91688298
   -154.

I have Jack's pulled up here on another window, hopefully the comments should underline that I'm more than capable of
both understanding what it's doing to a point where I could have recreated... but, I'm also a large part of the
reason he can do this, so, I'm ok with that